# Fast deployment with pre-built images from GitHub Container Registry
# Usage: docker-compose -f docker-compose.prebuilt.yml up -d

services:
  nginx:
    image: ghcr.io/smol-kitten/cat-waf-nginx:latest
    container_name: waf-nginx
    environment:
      - TZ=${TZ:-Europe/Berlin}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/modsecurity/coreruleset:/etc/nginx/modsecurity/coreruleset
      - ./nginx/modsecurity/custom-rules:/etc/nginx/modsecurity/custom-rules
      - ./nginx/error-pages:/usr/share/nginx/error-pages
      - ./error-pages:/usr/share/nginx/html/errors
      - ./logs/nginx:/var/log/nginx
      - ./logs/modsec:/var/log/modsec
      - ./certs:/etc/nginx/certs
      - ./data/geoip:/usr/share/GeoIP
      - nginx-htpasswd:/etc/nginx/htpasswd
    networks:
      - waf-network
    restart: unless-stopped
    depends_on:
      dashboard:
        condition: service_healthy
      default-backend:
        condition: service_started
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  dashboard:
    image: ghcr.io/smol-kitten/cat-waf-dashboard:latest
    container_name: waf-dashboard
    environment:
      TZ: ${TZ:-Europe/Berlin}
      DB_HOST: mariadb
      DB_NAME: waf_db
      DB_USER: waf_user
      DB_PASSWORD: ${DB_PASSWORD:-changeme}
      DASHBOARD_API_KEY: ${DASHBOARD_API_KEY:-change-this-default-token}
    volumes:
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./logs/modsec:/var/log/modsec
      - ./logs/nginx:/var/log/nginx
      - nginx-htpasswd:/etc/nginx/htpasswd
    networks:
      - waf-network
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  web-dashboard:
    image: ghcr.io/smol-kitten/cat-waf-web-dashboard:latest
    container_name: waf-web-dashboard
    ports:
      - "8080:80"
    networks:
      - waf-network
    restart: unless-stopped
    depends_on:
      - dashboard
    environment:
      API_URL: http://dashboard:80
      DASHBOARD_API_KEY: ${DASHBOARD_API_KEY:-change-this-default-token}
      TZ: ${TZ:-Europe/Berlin}
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

  mariadb:
    image: mariadb:11.8.2
    container_name: waf-mariadb
    environment:
      TZ: ${TZ:-Europe/Berlin}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-changeme}
      MYSQL_DATABASE: waf_db
      MYSQL_USER: waf_user
      MYSQL_PASSWORD: ${DB_PASSWORD:-changeme}
    volumes:
      - ./mariadb/init:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql
    networks:
      - waf-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  fail2ban:
    image: ghcr.io/smol-kitten/cat-waf-fail2ban:latest
    container_name: waf-fail2ban
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./logs/nginx:/var/log/nginx:ro
      - ./logs/modsec:/var/log/modsec:ro
      - ./nginx/banlist.conf:/etc/nginx/banlist.conf
      - ./fail2ban/banlist.conf:/etc/fail2ban/action.d/banlist.conf
    networks:
      - waf-network
    restart: unless-stopped
    depends_on:
      - nginx

  default-backend:
    image: nginx:alpine
    container_name: waf-default-backend
    command: /bin/sh -c "apk add --no-cache wget && wget https://raw.githubusercontent.com/smol-kitten/cat-waf/refs/heads/main/backends/default/index.html -O /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
    networks:
      - waf-network
    restart: unless-stopped

  acme:
    image: neilpang/acme.sh:latest
    container_name: waf-acme
    volumes:
      # Certificate storage (volume for persistence)
      - waf-certs:/acme.sh
      # NGINX config (read-only via volume)
      - waf-nginx-conf:/etc/nginx/conf.d:ro
    networks:
      - waf-network
    environment:
      - ACME_SH_EMAIL=${ACME_EMAIL:-admin@example.com}
      - TZ=${TZ:-Europe/Berlin}
    command: daemon
    restart: unless-stopped

  log-parser:
    image: ghcr.io/smol-kitten/cat-waf-log-parser:latest
    container_name: waf-log-parser
    environment:
      TZ: ${TZ:-Europe/Berlin}
      DB_HOST: mariadb
      DB_NAME: waf_db
      DB_USER: waf_user
      DB_PASSWORD: ${DB_PASSWORD:-changeme}
    volumes:
      - ./logs/nginx:/var/log/nginx:ro
      - ./logs/modsec:/var/log/modsec:ro
    networks:
      - waf-network
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy

networks:
  waf-network:
    driver: bridge

volumes:
  nginx-htpasswd:
  waf-certs:
  waf-nginx-conf:
