# Fast deployment with pre-built images from GitHub Container Registry
# Usage: docker-compose -f docker-compose.prebuilt.yml up -d

services:
  nginx:
    image: ghcr.io/smol-kitten/cat-waf-nginx:latest
    container_name: waf-nginx
    environment:
      - TZ=${TZ:-Europe/Berlin}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # All configuration now in volumes (managed via Docker)
      - waf-nginx-conf:/etc/nginx/conf.d
      - waf-nginx-sites:/etc/nginx/sites-enabled
      - waf-nginx-modsecurity:/etc/nginx/modsecurity
      # Data volumes (persistent across deployments)
      - waf-logs:/var/log
      - waf-certs:/etc/nginx/certs
      - waf-nginx-cache:/var/cache/nginx
      - waf-fail2ban:/etc/fail2ban
    networks:
      - waf-network
      - backend-network
    restart: unless-stopped
    depends_on:
      dashboard:
        condition: service_healthy
      default-backend:
        condition: service_started
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  dashboard:
    image: ghcr.io/smol-kitten/cat-waf-dashboard:latest
    container_name: waf-dashboard
    volumes:
      # Data volumes (read-only access to logs)
      - waf-logs:/var/log
      # Configuration access (via volumes)
      - waf-nginx-sites:/etc/nginx/sites-enabled
      - waf-fail2ban:/etc/fail2ban
      - waf-nginx-cache:/var/cache/nginx
      - fail2ban-socket:/var/run/fail2ban
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - waf-network
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
      migration-runner:
        condition: service_completed_successfully
    environment:
      TZ: ${TZ:-Europe/Berlin}
      DB_HOST: mariadb
      DB_NAME: waf_db
      DB_USER: waf_user
      DB_PASSWORD: ${DB_PASSWORD:-changeme}
      DASHBOARD_API_KEY: ${DASHBOARD_API_KEY:-change-this-default-token}
      # Cloudflare API credentials (for zone auto-detection)
      # Recommended: Use API Token with Zone:Read permission
      # Legacy: Use CF_API_KEY + CF_EMAIL (from ACME DNS challenge config)
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN:-}
      CLOUDFLARE_API_KEY: ${CF_API_KEY:-}
      CLOUDFLARE_EMAIL: ${CF_EMAIL:-}
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  fail2ban:
    image: ghcr.io/smol-kitten/cat-waf-fail2ban:latest
    container_name: waf-fail2ban
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      # Configuration files (consolidated into single volume)
      - waf-fail2ban:/etc/fail2ban
      # Data volumes (persistent logs - read-only)
      - waf-logs:/mnt/logs:ro
      # Socket for communication
      - fail2ban-socket:/var/run/fail2ban
    networks:
      - waf-network
    restart: unless-stopped
    depends_on:
      - nginx

  web-dashboard:
    image: ghcr.io/smol-kitten/cat-waf-web-dashboard:latest
    container_name: waf-web-dashboard
    ports:
      - "8080:80"
    networks:
      - waf-network
    restart: unless-stopped
    depends_on:
      - dashboard
    environment:
      API_URL: http://dashboard:80
      DASHBOARD_API_KEY: ${DASHBOARD_API_KEY:-change-this-default-token}
      TZ: ${TZ:-Europe/Berlin}
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

  mariadb:
    image: mariadb:latest
    container_name: waf-mariadb
    environment:
      TZ: ${TZ:-Europe/Berlin}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-changeme}
      MYSQL_DATABASE: waf_db
      MYSQL_USER: waf_user
      MYSQL_PASSWORD: ${DB_PASSWORD:-changeme}
    volumes:
      # Database data (volume for persistence)
      - waf-mysql-data:/var/lib/mysql
      # Shared volume for init scripts
      - waf-mariadb-init:/docker-entrypoint-initdb.d
    networks:
      - waf-network
    restart: unless-stopped
    depends_on:
      mariadb-init:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  mariadb-init:
    image: alpine:latest
    container_name: waf-mariadb-init
    command: >
      sh -c '
      echo "Downloading database schema and migrations..." &&
      wget -q https://raw.githubusercontent.com/smol-kitten/cat-waf/main/mariadb/init/01-complete-schema.sql -O /init/01-complete-schema.sql &&
      wget -q https://raw.githubusercontent.com/smol-kitten/cat-waf/main/mariadb/init/06-migration-redirect-cf-ratelimit.sql -O /init/06-migration-redirect-cf-ratelimit.sql &&
      echo "Files downloaded successfully!" &&
      ls -lh /init/
      '
    volumes:
      # Shared volume with MariaDB for init scripts
      - waf-mariadb-init:/init
    networks:
      - waf-network

  migration-runner:
    image: mariadb:latest
    container_name: waf-migration-runner
    command: >
      sh -c '
      echo "Waiting for MariaDB to be ready..." &&
      sleep 5 &&
      echo "Applying migrations..." &&
      for migration in /migrations/*-migration-*.sql; do
        if [ -f "$$migration" ]; then
          echo "  → Applying: $$(basename $$migration)" &&
          mariadb -h mariadb -u waf_user -p$$DB_PASSWORD waf_db < "$$migration" 2>&1 | grep -v "Warning: Using a password" || true
        fi
      done &&
      echo "✅ Migrations completed!" &&
      echo "Verifying schema..." &&
      mariadb -h mariadb -u waf_user -p$$DB_PASSWORD waf_db -e "SELECT COUNT(*) as column_count FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = '"'"'waf_db'"'"' AND TABLE_NAME = '"'"'sites'"'"';" 2>&1 | grep -v "Warning" &&
      echo "Schema verification complete!"
      '
    environment:
      DB_PASSWORD: ${DB_PASSWORD:-changeme}
    volumes:
      # Mount init scripts volume to access migrations
      - waf-mariadb-init:/migrations:ro
    networks:
      - waf-network
    depends_on:
      mariadb:
        condition: service_healthy
      mariadb-init:
        condition: service_completed_successfully
    restart: "no"

  default-backend:
    image: nginx:alpine
    container_name: waf-default-backend
    command: /bin/sh -c "apk add --no-cache wget && wget https://raw.githubusercontent.com/smol-kitten/cat-waf/refs/heads/main/backends/default/index.html -O /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
    networks:
      - waf-network
    restart: unless-stopped

  acme:
    image: neilpang/acme.sh:latest
    container_name: waf-acme
    volumes:
      # Certificate storage (volume for persistence)
      - waf-certs:/acme.sh
      # NGINX config (read-only via volume)
      - waf-nginx-conf:/etc/nginx/conf.d:ro
    networks:
      - waf-network
    environment:
      - ACME_SH_EMAIL=${ACME_EMAIL:-admin@example.com}
      - TZ=${TZ:-Europe/Berlin}
      # Cloudflare credentials for DNS-01 challenge
      # acme.sh expects CF_Token (API Token) or CF_Key + CF_Email (Global API Key)
      - CF_Token=${CLOUDFLARE_API_TOKEN:-}
      - CF_Key=${CF_API_KEY:-}
      - CF_Email=${CF_EMAIL:-}
    command: daemon
    restart: unless-stopped

  log-parser:
    image: ghcr.io/smol-kitten/cat-waf-log-parser:latest
    container_name: waf-log-parser
    environment:
      TZ: ${TZ:-Europe/Berlin}
      DB_HOST: mariadb
      DB_NAME: waf_db
      DB_USER: waf_user
      DB_PASSWORD: ${DB_PASSWORD:-changeme}
    volumes:
      # Data volumes (read-only access to logs)
      - waf-logs:/var/log:ro
    networks:
      - waf-network
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy

networks:
  waf-network:
    driver: bridge
  backend-network:
    driver: bridge

volumes:
  # MySQL/MariaDB data volume
  waf-mysql-data:
    name: waf-mysql-data
  # MariaDB init scripts volume (shared with init container)
  waf-mariadb-init:
    name: waf-mariadb-init
  # Fail2ban configuration and state
  waf-fail2ban:
    name: waf-fail2ban
  # NGINX cache directory
  waf-nginx-cache:
    name: waf-nginx-cache
  # SSL/TLS certificates
  waf-certs:
    name: waf-certs
  # Log files (nginx, modsec, etc.)
  waf-logs:
    name: waf-logs
  # Web dashboard data
  waf-web-dashboard:
    name: waf-web-dashboard
  # NGINX main configuration
  waf-nginx-conf:
    name: waf-nginx-conf
  # NGINX site configurations
  waf-nginx-sites:
    name: waf-nginx-sites
  # ModSecurity configuration and rules
  waf-nginx-modsecurity:
    name: waf-nginx-modsecurity
  # Fail2ban socket for communication
  fail2ban-socket:
    name: fail2ban-socket
