name: Build and Push Docker Images

on:
  push:
    branches:
      - main
      - dev
    tags:
      - 'v*.*.*'
    paths:
      - 'nginx/**'
      - 'dashboard/**'
      - 'web-dashboard/**'
      - 'fail2ban/**'
      - 'log-parser/**'
      - 'mariadb/**'
      - 'updater/**'
      - '.gitea/workflows/build-images.yml'
  workflow_dispatch:

env:
  GITEA_REGISTRY: git.catboy.systems
  GITHUB_REGISTRY: ghcr.io
  GITEA_IMAGE_PREFIX: git.catboy.systems/${{ github.repository_owner }}/cat-waf
  GITHUB_IMAGE_PREFIX: ghcr.io/${{ github.repository_owner }}/cat-waf

jobs:
  build-nginx:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Gitea Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITEA_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GT_TOKEN }}
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ secrets.GH_USER }}
          password: ${{ secrets.GH_TOKEN }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.GITEA_IMAGE_PREFIX }}-nginx
            ${{ env.GITHUB_IMAGE_PREFIX }}-nginx
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=nightly,enable=${{ github.ref == 'refs/heads/dev' }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          flavor: |
            latest=auto
          labels: |
            org.opencontainers.image.description=CatWAF NGINX with ModSecurity
            maintainer=${{ github.repository_owner }}
      
      - name: Build image locally
        uses: docker/build-push-action@v5
        with:
          context: ./nginx
          push: false
          load: true
          tags: cat-waf-nginx:build
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Slim the image
        uses: kitabisa/docker-slim-action@v1
        env:
          DSLIM_HTTP_PROBE: false
        with:
          target: cat-waf-nginx:build
          tag: "slim"
      
      - name: Create Dockerfile for slimmed image push
        run: |
          echo "FROM cat-waf-nginx:slim" > Dockerfile.slim
      
      - name: Push slimmed image to both registries
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.slim
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-migration-runner:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Gitea Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITEA_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GT_TOKEN }}
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ secrets.GH_USER }}
          password: ${{ secrets.GH_TOKEN }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.GITEA_IMAGE_PREFIX }}-migration-runner
            ${{ env.GITHUB_IMAGE_PREFIX }}-migration-runner
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=nightly,enable=${{ github.ref == 'refs/heads/dev' }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      
      - name: Build image locally
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./mariadb/Dockerfile
          push: false
          load: true
          tags: cat-waf-migration-runner:build
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Slim the image
        uses: kitabisa/docker-slim-action@v1
        env:
          DSLIM_HTTP_PROBE: false
        with:
          target: cat-waf-migration-runner:build
          tag: "slim"
      
      - name: Create Dockerfile for slimmed image push
        run: |
          echo "FROM cat-waf-migration-runner:slim" > Dockerfile.slim
      
      - name: Push slimmed image to both registries
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.slim
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-dashboard:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Gitea Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITEA_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GT_TOKEN }}
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ secrets.GH_USER }}
          password: ${{ secrets.GH_TOKEN }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.GITEA_IMAGE_PREFIX }}-dashboard
            ${{ env.GITHUB_IMAGE_PREFIX }}-dashboard
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=nightly,enable=${{ github.ref == 'refs/heads/dev' }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      
      - name: Build image locally
        uses: docker/build-push-action@v5
        with:
          context: ./dashboard
          push: false
          load: true
          tags: cat-waf-dashboard:build
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Slim the image
        uses: kitabisa/docker-slim-action@v1
        env:
          DSLIM_HTTP_PROBE: false
        with:
          target: cat-waf-dashboard:build
          tag: "slim"
      
      - name: Create Dockerfile for slimmed image push
        run: |
          echo "FROM cat-waf-dashboard:slim" > Dockerfile.slim
      
      - name: Push slimmed image to both registries
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.slim
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-web-dashboard:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Gitea Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITEA_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GT_TOKEN }}
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ secrets.GH_USER }}
          password: ${{ secrets.GH_TOKEN }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.GITEA_IMAGE_PREFIX }}-web-dashboard
            ${{ env.GITHUB_IMAGE_PREFIX }}-web-dashboard
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=nightly,enable=${{ github.ref == 'refs/heads/dev' }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      
      - name: Build image locally
        uses: docker/build-push-action@v5
        with:
          context: ./web-dashboard
          push: false
          load: true
          tags: cat-waf-web-dashboard:build
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Slim the image
        uses: kitabisa/docker-slim-action@v1
        env:
          DSLIM_HTTP_PROBE: false
        with:
          target: cat-waf-web-dashboard:build
          tag: "slim"
      
      - name: Create Dockerfile for slimmed image push
        run: |
          echo "FROM cat-waf-web-dashboard:slim" > Dockerfile.slim
      
      - name: Push slimmed image to both registries
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.slim
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-fail2ban:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Gitea Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITEA_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GT_TOKEN }}
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ secrets.GH_USER }}
          password: ${{ secrets.GH_TOKEN }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.GITEA_IMAGE_PREFIX }}-fail2ban
            ${{ env.GITHUB_IMAGE_PREFIX }}-fail2ban
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=nightly,enable=${{ github.ref == 'refs/heads/dev' }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      
      - name: Build image locally
        uses: docker/build-push-action@v5
        with:
          context: ./fail2ban
          push: false
          load: true
          tags: cat-waf-fail2ban:build
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Slim the image
        uses: kitabisa/docker-slim-action@v1
        env:
          DSLIM_HTTP_PROBE: false
        with:
          target: cat-waf-fail2ban:build
          tag: "slim"
      
      - name: Create Dockerfile for slimmed image push
        run: |
          echo "FROM cat-waf-fail2ban:slim" > Dockerfile.slim
      
      - name: Push slimmed image to both registries
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.slim
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-log-parser:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Gitea Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITEA_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GT_TOKEN }}
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ secrets.GH_USER }}
          password: ${{ secrets.GH_TOKEN }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.GITEA_IMAGE_PREFIX }}-log-parser
            ${{ env.GITHUB_IMAGE_PREFIX }}-log-parser
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=nightly,enable=${{ github.ref == 'refs/heads/dev' }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      
      - name: Build image locally
        uses: docker/build-push-action@v5
        with:
          context: ./log-parser
          push: false
          load: true
          tags: cat-waf-log-parser:build
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Slim the image
        uses: kitabisa/docker-slim-action@v1
        env:
          DSLIM_HTTP_PROBE: false
        with:
          target: cat-waf-log-parser:build
          tag: "slim"
      
      - name: Create Dockerfile for slimmed image push
        run: |
          echo "FROM cat-waf-log-parser:slim" > Dockerfile.slim
      
      - name: Push slimmed image to both registries
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.slim
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-updater:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Gitea Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITEA_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GT_TOKEN }}
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ secrets.GH_USER }}
          password: ${{ secrets.GH_TOKEN }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.GITEA_IMAGE_PREFIX }}-updater
            ${{ env.GITHUB_IMAGE_PREFIX }}-updater
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=nightly,enable=${{ github.ref == 'refs/heads/dev' }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      
      - name: Build image locally
        uses: docker/build-push-action@v5
        with:
          context: ./updater
          push: false
          load: true
          tags: cat-waf-updater:build
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Slim the image
        uses: kitabisa/docker-slim-action@v1
        env:
          DSLIM_HTTP_PROBE: false
        with:
          target: cat-waf-updater:build
          tag: "slim"
      
      - name: Create Dockerfile for slimmed image push
        run: |
          echo "FROM cat-waf-updater:slim" > Dockerfile.slim
      
      - name: Push slimmed image to both registries
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.slim
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  cleanup:
    runs-on: self-hosted
    needs: [build-nginx, build-migration-runner, build-dashboard, build-web-dashboard, build-fail2ban, build-log-parser, build-updater]
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        package:
          - cat-waf-nginx
          - cat-waf-dashboard
          - cat-waf-web-dashboard
          - cat-waf-fail2ban
          - cat-waf-log-parser
          - cat-waf-migration-runner
          - cat-waf-updater
    steps:
      - name: Cleanup GitHub Container Registry
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          package: ${{ matrix.package }}
          delete-untagged: true
          older-than: 7 days
          keep-n-tagged: 5
          token: ${{ secrets.GH_TOKEN }}
        continue-on-error: true
      
      - name: Cleanup Gitea Container Registry
        run: |
          echo "Gitea registry cleanup for ${{ matrix.package }} would go here"
        continue-on-error: true
      
      - name: Cleanup local Docker images
        run: |
          docker images --filter "dangling=true" -q | tail -n +4 | xargs -r docker rmi || true
        continue-on-error: true
